# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sxf/Desktop/RelativeLocation/demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sxf/Desktop/RelativeLocation/demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sxf/Desktop/RelativeLocation/demo/CMakeFiles /home/sxf/Desktop/RelativeLocation/demo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sxf/Desktop/RelativeLocation/demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

ED_Lib/ArucoDetect.o: ED_Lib/ArucoDetect.cpp.o
.PHONY : ED_Lib/ArucoDetect.o

# target to build an object file
ED_Lib/ArucoDetect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/ArucoDetect.cpp.o
.PHONY : ED_Lib/ArucoDetect.cpp.o

ED_Lib/ArucoDetect.i: ED_Lib/ArucoDetect.cpp.i
.PHONY : ED_Lib/ArucoDetect.i

# target to preprocess a source file
ED_Lib/ArucoDetect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/ArucoDetect.cpp.i
.PHONY : ED_Lib/ArucoDetect.cpp.i

ED_Lib/ArucoDetect.s: ED_Lib/ArucoDetect.cpp.s
.PHONY : ED_Lib/ArucoDetect.s

# target to generate assembly for a file
ED_Lib/ArucoDetect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/ArucoDetect.cpp.s
.PHONY : ED_Lib/ArucoDetect.cpp.s

ED_Lib/ED.o: ED_Lib/ED.cpp.o
.PHONY : ED_Lib/ED.o

# target to build an object file
ED_Lib/ED.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/ED.cpp.o
.PHONY : ED_Lib/ED.cpp.o

ED_Lib/ED.i: ED_Lib/ED.cpp.i
.PHONY : ED_Lib/ED.i

# target to preprocess a source file
ED_Lib/ED.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/ED.cpp.i
.PHONY : ED_Lib/ED.cpp.i

ED_Lib/ED.s: ED_Lib/ED.cpp.s
.PHONY : ED_Lib/ED.s

# target to generate assembly for a file
ED_Lib/ED.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/ED.cpp.s
.PHONY : ED_Lib/ED.cpp.s

ED_Lib/EDCircles.o: ED_Lib/EDCircles.cpp.o
.PHONY : ED_Lib/EDCircles.o

# target to build an object file
ED_Lib/EDCircles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDCircles.cpp.o
.PHONY : ED_Lib/EDCircles.cpp.o

ED_Lib/EDCircles.i: ED_Lib/EDCircles.cpp.i
.PHONY : ED_Lib/EDCircles.i

# target to preprocess a source file
ED_Lib/EDCircles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDCircles.cpp.i
.PHONY : ED_Lib/EDCircles.cpp.i

ED_Lib/EDCircles.s: ED_Lib/EDCircles.cpp.s
.PHONY : ED_Lib/EDCircles.s

# target to generate assembly for a file
ED_Lib/EDCircles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDCircles.cpp.s
.PHONY : ED_Lib/EDCircles.cpp.s

ED_Lib/EDColor.o: ED_Lib/EDColor.cpp.o
.PHONY : ED_Lib/EDColor.o

# target to build an object file
ED_Lib/EDColor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDColor.cpp.o
.PHONY : ED_Lib/EDColor.cpp.o

ED_Lib/EDColor.i: ED_Lib/EDColor.cpp.i
.PHONY : ED_Lib/EDColor.i

# target to preprocess a source file
ED_Lib/EDColor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDColor.cpp.i
.PHONY : ED_Lib/EDColor.cpp.i

ED_Lib/EDColor.s: ED_Lib/EDColor.cpp.s
.PHONY : ED_Lib/EDColor.s

# target to generate assembly for a file
ED_Lib/EDColor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDColor.cpp.s
.PHONY : ED_Lib/EDColor.cpp.s

ED_Lib/EDLines.o: ED_Lib/EDLines.cpp.o
.PHONY : ED_Lib/EDLines.o

# target to build an object file
ED_Lib/EDLines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDLines.cpp.o
.PHONY : ED_Lib/EDLines.cpp.o

ED_Lib/EDLines.i: ED_Lib/EDLines.cpp.i
.PHONY : ED_Lib/EDLines.i

# target to preprocess a source file
ED_Lib/EDLines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDLines.cpp.i
.PHONY : ED_Lib/EDLines.cpp.i

ED_Lib/EDLines.s: ED_Lib/EDLines.cpp.s
.PHONY : ED_Lib/EDLines.s

# target to generate assembly for a file
ED_Lib/EDLines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDLines.cpp.s
.PHONY : ED_Lib/EDLines.cpp.s

ED_Lib/EDPF.o: ED_Lib/EDPF.cpp.o
.PHONY : ED_Lib/EDPF.o

# target to build an object file
ED_Lib/EDPF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDPF.cpp.o
.PHONY : ED_Lib/EDPF.cpp.o

ED_Lib/EDPF.i: ED_Lib/EDPF.cpp.i
.PHONY : ED_Lib/EDPF.i

# target to preprocess a source file
ED_Lib/EDPF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDPF.cpp.i
.PHONY : ED_Lib/EDPF.cpp.i

ED_Lib/EDPF.s: ED_Lib/EDPF.cpp.s
.PHONY : ED_Lib/EDPF.s

# target to generate assembly for a file
ED_Lib/EDPF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/EDPF.cpp.s
.PHONY : ED_Lib/EDPF.cpp.s

ED_Lib/NFA.o: ED_Lib/NFA.cpp.o
.PHONY : ED_Lib/NFA.o

# target to build an object file
ED_Lib/NFA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/NFA.cpp.o
.PHONY : ED_Lib/NFA.cpp.o

ED_Lib/NFA.i: ED_Lib/NFA.cpp.i
.PHONY : ED_Lib/NFA.i

# target to preprocess a source file
ED_Lib/NFA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/NFA.cpp.i
.PHONY : ED_Lib/NFA.cpp.i

ED_Lib/NFA.s: ED_Lib/NFA.cpp.s
.PHONY : ED_Lib/NFA.s

# target to generate assembly for a file
ED_Lib/NFA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ED_Lib/NFA.cpp.s
.PHONY : ED_Lib/NFA.cpp.s

aamed/Contours.o: aamed/Contours.cpp.o
.PHONY : aamed/Contours.o

# target to build an object file
aamed/Contours.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Contours.cpp.o
.PHONY : aamed/Contours.cpp.o

aamed/Contours.i: aamed/Contours.cpp.i
.PHONY : aamed/Contours.i

# target to preprocess a source file
aamed/Contours.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Contours.cpp.i
.PHONY : aamed/Contours.cpp.i

aamed/Contours.s: aamed/Contours.cpp.s
.PHONY : aamed/Contours.s

# target to generate assembly for a file
aamed/Contours.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Contours.cpp.s
.PHONY : aamed/Contours.cpp.s

aamed/EllipseNonMaximumSuppression.o: aamed/EllipseNonMaximumSuppression.cpp.o
.PHONY : aamed/EllipseNonMaximumSuppression.o

# target to build an object file
aamed/EllipseNonMaximumSuppression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/EllipseNonMaximumSuppression.cpp.o
.PHONY : aamed/EllipseNonMaximumSuppression.cpp.o

aamed/EllipseNonMaximumSuppression.i: aamed/EllipseNonMaximumSuppression.cpp.i
.PHONY : aamed/EllipseNonMaximumSuppression.i

# target to preprocess a source file
aamed/EllipseNonMaximumSuppression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/EllipseNonMaximumSuppression.cpp.i
.PHONY : aamed/EllipseNonMaximumSuppression.cpp.i

aamed/EllipseNonMaximumSuppression.s: aamed/EllipseNonMaximumSuppression.cpp.s
.PHONY : aamed/EllipseNonMaximumSuppression.s

# target to generate assembly for a file
aamed/EllipseNonMaximumSuppression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/EllipseNonMaximumSuppression.cpp.s
.PHONY : aamed/EllipseNonMaximumSuppression.cpp.s

aamed/FLED.o: aamed/FLED.cpp.o
.PHONY : aamed/FLED.o

# target to build an object file
aamed/FLED.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED.cpp.o
.PHONY : aamed/FLED.cpp.o

aamed/FLED.i: aamed/FLED.cpp.i
.PHONY : aamed/FLED.i

# target to preprocess a source file
aamed/FLED.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED.cpp.i
.PHONY : aamed/FLED.cpp.i

aamed/FLED.s: aamed/FLED.cpp.s
.PHONY : aamed/FLED.s

# target to generate assembly for a file
aamed/FLED.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED.cpp.s
.PHONY : aamed/FLED.cpp.s

aamed/FLED_Initialization.o: aamed/FLED_Initialization.cpp.o
.PHONY : aamed/FLED_Initialization.o

# target to build an object file
aamed/FLED_Initialization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_Initialization.cpp.o
.PHONY : aamed/FLED_Initialization.cpp.o

aamed/FLED_Initialization.i: aamed/FLED_Initialization.cpp.i
.PHONY : aamed/FLED_Initialization.i

# target to preprocess a source file
aamed/FLED_Initialization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_Initialization.cpp.i
.PHONY : aamed/FLED_Initialization.cpp.i

aamed/FLED_Initialization.s: aamed/FLED_Initialization.cpp.s
.PHONY : aamed/FLED_Initialization.s

# target to generate assembly for a file
aamed/FLED_Initialization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_Initialization.cpp.s
.PHONY : aamed/FLED_Initialization.cpp.s

aamed/FLED_PrivateFunctions.o: aamed/FLED_PrivateFunctions.cpp.o
.PHONY : aamed/FLED_PrivateFunctions.o

# target to build an object file
aamed/FLED_PrivateFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_PrivateFunctions.cpp.o
.PHONY : aamed/FLED_PrivateFunctions.cpp.o

aamed/FLED_PrivateFunctions.i: aamed/FLED_PrivateFunctions.cpp.i
.PHONY : aamed/FLED_PrivateFunctions.i

# target to preprocess a source file
aamed/FLED_PrivateFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_PrivateFunctions.cpp.i
.PHONY : aamed/FLED_PrivateFunctions.cpp.i

aamed/FLED_PrivateFunctions.s: aamed/FLED_PrivateFunctions.cpp.s
.PHONY : aamed/FLED_PrivateFunctions.s

# target to generate assembly for a file
aamed/FLED_PrivateFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_PrivateFunctions.cpp.s
.PHONY : aamed/FLED_PrivateFunctions.cpp.s

aamed/FLED_drawAndWriteFunctions.o: aamed/FLED_drawAndWriteFunctions.cpp.o
.PHONY : aamed/FLED_drawAndWriteFunctions.o

# target to build an object file
aamed/FLED_drawAndWriteFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_drawAndWriteFunctions.cpp.o
.PHONY : aamed/FLED_drawAndWriteFunctions.cpp.o

aamed/FLED_drawAndWriteFunctions.i: aamed/FLED_drawAndWriteFunctions.cpp.i
.PHONY : aamed/FLED_drawAndWriteFunctions.i

# target to preprocess a source file
aamed/FLED_drawAndWriteFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_drawAndWriteFunctions.cpp.i
.PHONY : aamed/FLED_drawAndWriteFunctions.cpp.i

aamed/FLED_drawAndWriteFunctions.s: aamed/FLED_drawAndWriteFunctions.cpp.s
.PHONY : aamed/FLED_drawAndWriteFunctions.s

# target to generate assembly for a file
aamed/FLED_drawAndWriteFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/FLED_drawAndWriteFunctions.cpp.s
.PHONY : aamed/FLED_drawAndWriteFunctions.cpp.s

aamed/Group.o: aamed/Group.cpp.o
.PHONY : aamed/Group.o

# target to build an object file
aamed/Group.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Group.cpp.o
.PHONY : aamed/Group.cpp.o

aamed/Group.i: aamed/Group.cpp.i
.PHONY : aamed/Group.i

# target to preprocess a source file
aamed/Group.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Group.cpp.i
.PHONY : aamed/Group.cpp.i

aamed/Group.s: aamed/Group.cpp.s
.PHONY : aamed/Group.s

# target to generate assembly for a file
aamed/Group.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Group.cpp.s
.PHONY : aamed/Group.cpp.s

aamed/LinkMatrix.o: aamed/LinkMatrix.cpp.o
.PHONY : aamed/LinkMatrix.o

# target to build an object file
aamed/LinkMatrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/LinkMatrix.cpp.o
.PHONY : aamed/LinkMatrix.cpp.o

aamed/LinkMatrix.i: aamed/LinkMatrix.cpp.i
.PHONY : aamed/LinkMatrix.i

# target to preprocess a source file
aamed/LinkMatrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/LinkMatrix.cpp.i
.PHONY : aamed/LinkMatrix.cpp.i

aamed/LinkMatrix.s: aamed/LinkMatrix.cpp.s
.PHONY : aamed/LinkMatrix.s

# target to generate assembly for a file
aamed/LinkMatrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/LinkMatrix.cpp.s
.PHONY : aamed/LinkMatrix.cpp.s

aamed/Node_FC.o: aamed/Node_FC.cpp.o
.PHONY : aamed/Node_FC.o

# target to build an object file
aamed/Node_FC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Node_FC.cpp.o
.PHONY : aamed/Node_FC.cpp.o

aamed/Node_FC.i: aamed/Node_FC.cpp.i
.PHONY : aamed/Node_FC.i

# target to preprocess a source file
aamed/Node_FC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Node_FC.cpp.i
.PHONY : aamed/Node_FC.cpp.i

aamed/Node_FC.s: aamed/Node_FC.cpp.s
.PHONY : aamed/Node_FC.s

# target to generate assembly for a file
aamed/Node_FC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Node_FC.cpp.s
.PHONY : aamed/Node_FC.cpp.s

aamed/Segmentation.o: aamed/Segmentation.cpp.o
.PHONY : aamed/Segmentation.o

# target to build an object file
aamed/Segmentation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Segmentation.cpp.o
.PHONY : aamed/Segmentation.cpp.o

aamed/Segmentation.i: aamed/Segmentation.cpp.i
.PHONY : aamed/Segmentation.i

# target to preprocess a source file
aamed/Segmentation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Segmentation.cpp.i
.PHONY : aamed/Segmentation.cpp.i

aamed/Segmentation.s: aamed/Segmentation.cpp.s
.PHONY : aamed/Segmentation.s

# target to generate assembly for a file
aamed/Segmentation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Segmentation.cpp.s
.PHONY : aamed/Segmentation.cpp.s

aamed/Validation.o: aamed/Validation.cpp.o
.PHONY : aamed/Validation.o

# target to build an object file
aamed/Validation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Validation.cpp.o
.PHONY : aamed/Validation.cpp.o

aamed/Validation.i: aamed/Validation.cpp.i
.PHONY : aamed/Validation.i

# target to preprocess a source file
aamed/Validation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Validation.cpp.i
.PHONY : aamed/Validation.cpp.i

aamed/Validation.s: aamed/Validation.cpp.s
.PHONY : aamed/Validation.s

# target to generate assembly for a file
aamed/Validation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/Validation.cpp.s
.PHONY : aamed/Validation.cpp.s

aamed/adaptApproxPolyDP.o: aamed/adaptApproxPolyDP.cpp.o
.PHONY : aamed/adaptApproxPolyDP.o

# target to build an object file
aamed/adaptApproxPolyDP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/adaptApproxPolyDP.cpp.o
.PHONY : aamed/adaptApproxPolyDP.cpp.o

aamed/adaptApproxPolyDP.i: aamed/adaptApproxPolyDP.cpp.i
.PHONY : aamed/adaptApproxPolyDP.i

# target to preprocess a source file
aamed/adaptApproxPolyDP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/adaptApproxPolyDP.cpp.i
.PHONY : aamed/adaptApproxPolyDP.cpp.i

aamed/adaptApproxPolyDP.s: aamed/adaptApproxPolyDP.cpp.s
.PHONY : aamed/adaptApproxPolyDP.s

# target to generate assembly for a file
aamed/adaptApproxPolyDP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/adaptApproxPolyDP.cpp.s
.PHONY : aamed/adaptApproxPolyDP.cpp.s

aamed/adaptApproximateContours.o: aamed/adaptApproximateContours.cpp.o
.PHONY : aamed/adaptApproximateContours.o

# target to build an object file
aamed/adaptApproximateContours.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/adaptApproximateContours.cpp.o
.PHONY : aamed/adaptApproximateContours.cpp.o

aamed/adaptApproximateContours.i: aamed/adaptApproximateContours.cpp.i
.PHONY : aamed/adaptApproximateContours.i

# target to preprocess a source file
aamed/adaptApproximateContours.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/adaptApproximateContours.cpp.i
.PHONY : aamed/adaptApproximateContours.cpp.i

aamed/adaptApproximateContours.s: aamed/adaptApproximateContours.cpp.s
.PHONY : aamed/adaptApproximateContours.s

# target to generate assembly for a file
aamed/adaptApproximateContours.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/aamed/adaptApproximateContours.cpp.s
.PHONY : aamed/adaptApproximateContours.cpp.s

ellipse.o: ellipse.cpp.o
.PHONY : ellipse.o

# target to build an object file
ellipse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ellipse.cpp.o
.PHONY : ellipse.cpp.o

ellipse.i: ellipse.cpp.i
.PHONY : ellipse.i

# target to preprocess a source file
ellipse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ellipse.cpp.i
.PHONY : ellipse.cpp.i

ellipse.s: ellipse.cpp.s
.PHONY : ellipse.s

# target to generate assembly for a file
ellipse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/ellipse.cpp.s
.PHONY : ellipse.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... demo"
	@echo "... ED_Lib/ArucoDetect.o"
	@echo "... ED_Lib/ArucoDetect.i"
	@echo "... ED_Lib/ArucoDetect.s"
	@echo "... ED_Lib/ED.o"
	@echo "... ED_Lib/ED.i"
	@echo "... ED_Lib/ED.s"
	@echo "... ED_Lib/EDCircles.o"
	@echo "... ED_Lib/EDCircles.i"
	@echo "... ED_Lib/EDCircles.s"
	@echo "... ED_Lib/EDColor.o"
	@echo "... ED_Lib/EDColor.i"
	@echo "... ED_Lib/EDColor.s"
	@echo "... ED_Lib/EDLines.o"
	@echo "... ED_Lib/EDLines.i"
	@echo "... ED_Lib/EDLines.s"
	@echo "... ED_Lib/EDPF.o"
	@echo "... ED_Lib/EDPF.i"
	@echo "... ED_Lib/EDPF.s"
	@echo "... ED_Lib/NFA.o"
	@echo "... ED_Lib/NFA.i"
	@echo "... ED_Lib/NFA.s"
	@echo "... aamed/Contours.o"
	@echo "... aamed/Contours.i"
	@echo "... aamed/Contours.s"
	@echo "... aamed/EllipseNonMaximumSuppression.o"
	@echo "... aamed/EllipseNonMaximumSuppression.i"
	@echo "... aamed/EllipseNonMaximumSuppression.s"
	@echo "... aamed/FLED.o"
	@echo "... aamed/FLED.i"
	@echo "... aamed/FLED.s"
	@echo "... aamed/FLED_Initialization.o"
	@echo "... aamed/FLED_Initialization.i"
	@echo "... aamed/FLED_Initialization.s"
	@echo "... aamed/FLED_PrivateFunctions.o"
	@echo "... aamed/FLED_PrivateFunctions.i"
	@echo "... aamed/FLED_PrivateFunctions.s"
	@echo "... aamed/FLED_drawAndWriteFunctions.o"
	@echo "... aamed/FLED_drawAndWriteFunctions.i"
	@echo "... aamed/FLED_drawAndWriteFunctions.s"
	@echo "... aamed/Group.o"
	@echo "... aamed/Group.i"
	@echo "... aamed/Group.s"
	@echo "... aamed/LinkMatrix.o"
	@echo "... aamed/LinkMatrix.i"
	@echo "... aamed/LinkMatrix.s"
	@echo "... aamed/Node_FC.o"
	@echo "... aamed/Node_FC.i"
	@echo "... aamed/Node_FC.s"
	@echo "... aamed/Segmentation.o"
	@echo "... aamed/Segmentation.i"
	@echo "... aamed/Segmentation.s"
	@echo "... aamed/Validation.o"
	@echo "... aamed/Validation.i"
	@echo "... aamed/Validation.s"
	@echo "... aamed/adaptApproxPolyDP.o"
	@echo "... aamed/adaptApproxPolyDP.i"
	@echo "... aamed/adaptApproxPolyDP.s"
	@echo "... aamed/adaptApproximateContours.o"
	@echo "... aamed/adaptApproximateContours.i"
	@echo "... aamed/adaptApproximateContours.s"
	@echo "... ellipse.o"
	@echo "... ellipse.i"
	@echo "... ellipse.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

